import os

from dotenv import load_dotenv


load_dotenv()


USERNAME = os.getenv("USERNAME")
PASSWORD = os.getenv("PASSWORD")

GATEWAY_IP = os.getenv("GATEWAY_IP")

LORA_FREQUENCY_PLAN = os.getenv("LORA_FREQUENCY_PLAN")

LORAWAN_EMAIL = os.getenv("LORAWAN_EMAIL")
LORAWAN_SERVER = os.getenv("LORAWAN_SERVER")

NETWORKWIFI_WIFI_SSID = os.getenv("NETWORKWIFI_WIFI_SSID")
NETWORKWIFI_WIFI_PASSWORD = os.getenv("NETWORKWIFI_WIFI_PASSWORD")

SYSTEM_PASSWORD = os.getenv("SYSTEM_PASSWORD")
SYSTEM_TIMEZONE = os.getenv("SYSTEM_TIMEZONE")

NETWORKCELLULAR_CELLULAR_APN = os.getenv(
    "NETWORKCELLULAR_CELLULAR_APN"
)

NETWORKCELLULAR_CELLULAR_USERNAME = os.getenv(
    "NETWORKCELLULAR_CELLULAR_USERNAME"
)

NETWORKCELLULAR_CELLULAR_PASSWORD = os.getenv(
    "NETWORKCELLULAR_CELLULAR_PASSWORD"
)

NETWORKCELLULAR_CELLULAR_PINCORE = os.getenv(
    "NETWORKCELLULAR_CELLULAR_PINCORE"
)
